name: Build and publish a Docker image to ghcr.io

on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [published]

  push:
    branches: feature/adding_docker_github_action

jobs:
  docker_ghcr_build_push:
    runs-on: ubuntu-20.04
    environment: container_registory
    env:
      NAME: $GITHUB_REPOSITORY
      TAG: $GITHUB_REF
    steps:
      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v1.5.0
        with:
          status: ${{ job.status }}
          channel: "#cosmos-hub-internal"
          steps: ${{ toJson(steps) }}
          message: Starting Gravity Delegation bot
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $GITHUB_REPOSITORY_OWNER
          password: ${{ secrets.CR_PAT }}
      - name: echo docker
        run: echo wtf  "$(which docker)"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "$NAME":"$TAG"
      - name: Docker Push
        run: docker push "$NAME":"$TAG"
